obj-m += my_hello.o

all:
	make -C $(HOME)/linux-dev/my_module/WSL2-Linux-Kernel-linux-msft-wsl-6.6.114.1 M=$(PWD) modules

clean:
	make -C $(HOME)/linux-dev/my_module/WSL2-Linux-Kernel-linux-msft-wsl-6.6.114.1 M=$(PWD) clean
